backend:
  name: github
  repo: Dogson/nervy

media_folder: static/img
public_folder: img
#logo_url: https://www.campusfrancosenegalais.org/assets/images/logoCFS.png
#site_url: https://www.campusfrancosenegalais.org/
#display_url: https://www.campusfrancosenegalais.org/

slug:
  encoding: ascii
  clean_accents: true

collections:
  - label: Pages
    name: pages
    editor:
      preview: false
    files:
      #Page d'accueil
      - label: Page d'accueil
        description: "Images / Texte de la page d'accueil"
        name: homepage
        file: src/content/pages/homepage.md
        fields:
          - { name: "type", widget: "hidden", label: "Type", default: "homepage" }
          - { name: "backgroundImage", label: "Image de fond", widget: "image" }
      - label: Gallerie
        description: "Images et légendes de la gallerie"
        name: gallery
        file: src/content/pages/gallery.md
        fields:
          - { name: "type", widget: "hidden", label: "Type", default: "gallery" }
          - { name: "backgroundImage", label: "Image de fond", widget: "image" }
          - name: "pictures"
            label: "Photos"
            widget: "list"
            fields:
              - {name: "picture", widget: "image", label: "Photo"}
              - {name: "label", label: "Légende", required: false}